
INSERT INTO blog_posts (title, slug, excerpt, content, image_url, category, published, created_at, updated_at) VALUES
('Как раскрутить трек в 2025 году', 'kak-raskrirutit-trek-2025', 'Актуальные методы продвижения музыки в 2025 году', 'Полное руководство по продвижению', 'https://cdn.poehali.dev/files/promotion.jpg', 'Продвижение', true, '2024-11-01 10:00:00', NOW()),
('Сколько прослушиваний в ТОП 1', 'skolko-proslushivaniy-v-top-1', 'Статистика 2025 года по чартам', 'Анализ чартов всех платформ', 'https://cdn.poehali.dev/files/81d2b3fc-e7ee-4995-b5b8-6fd9eb0b0ac8.png', 'Аналитика', true, '2024-11-05 12:00:00', NOW()),
('Как попасть в Spotify плейлисты', 'spotify-playlists-guide', 'Гайд по работе с кураторами плейлистов', 'Детальная инструкция', 'https://cdn.poehali.dev/files/spotify.jpg', 'Продвижение', true, '2024-10-28 09:00:00', NOW()),
('Монетизация музыки в 2025', 'monetization-2025', 'Все способы заработка для музыканта', 'От стриминга до мерча', 'https://cdn.poehali.dev/files/money.jpg', 'Монетизация', true, '2024-10-25 11:00:00', NOW()),
('TikTok для музыкантов', 'tiktok-for-musicians', 'Как использовать TikTok для продвижения', 'Вирусные стратегии 2025', 'https://cdn.poehali.dev/files/tiktok.jpg', 'Продвижение', true, '2024-10-20 14:00:00', NOW()),
('Авторские права и музыка', 'copyright-basics', 'Что нужно знать о защите своих треков', 'Юридический гайд', 'https://cdn.poehali.dev/files/copyright.jpg', 'Обучение', true, '2024-10-15 10:00:00', NOW()),
('Как записать первый трек', 'first-track-guide', 'Пошаговое руководство для начинающих', 'От идеи до релиза', 'https://cdn.poehali.dev/files/recording.jpg', 'Для начинающих', true, '2024-10-10 09:00:00', NOW()),
('Сведение и мастеринг: базовый гайд', 'mixing-mastering-basics', 'Основы работы со звуком', 'Для начинающих продюсеров', 'https://cdn.poehali.dev/files/mixing.jpg', 'Обучение', true, '2024-10-05 11:00:00', NOW()),
('Тренды музыки 2025', 'music-trends-2025', 'Какие жанры и стили популярны', 'Анализ рынка', 'https://cdn.poehali.dev/files/trends.jpg', 'Тренды', true, '2024-09-30 10:00:00', NOW()),
('Работа с лейблами', 'working-with-labels', 'Стоит ли подписывать контракт', 'Плюсы и минусы', 'https://cdn.poehali.dev/files/labels.jpg', 'Карьера', true, '2024-09-25 12:00:00', NOW()),
('Релиз-стратегия: сингл или альбом', 'single-vs-album', 'Что выбрать в 2025 году', 'Анализ эффективности', 'https://cdn.poehali.dev/files/release.jpg', 'Релизы', true, '2024-09-20 09:00:00', NOW()),
('Как собрать команду артиста', 'building-team', 'Менеджер, PR, продюсер - кто нужен', 'Гайд по делегированию', 'https://cdn.poehali.dev/files/team.jpg', 'Карьера', true, '2024-09-15 11:00:00', NOW()),
('Яндекс.Музыка: советы для артистов', 'yandex-music-tips', 'Как продвигаться на главной платформе РФ', 'Особенности алгоритмов', 'https://cdn.poehali.dev/files/yandex.jpg', 'Продвижение', true, '2024-09-10 10:00:00', NOW()),
('Концерты и туры: как начать', 'concerts-guide', 'От первого выступления к туру', 'Организация живых шоу', 'https://cdn.poehali.dev/files/concert.jpg', 'Карьера', true, '2024-09-05 14:00:00', NOW()),
('Создание мерча для артиста', 'merch-creation', 'Дополнительный доход от продукции', 'Идеи и производство', 'https://cdn.poehali.dev/files/merch.jpg', 'Монетизация', true, '2024-08-30 09:00:00', NOW()),
('SMM для музыкантов', 'smm-for-musicians', 'Соцсети как инструмент продвижения', 'Контент-стратегии', 'https://cdn.poehali.dev/files/smm.jpg', 'Продвижение', true, '2024-08-25 11:00:00', NOW()),
('Анализ конкурентов в музыке', 'competitor-analysis', 'Как учиться у успешных артистов', 'Метод бенчмаркинга', 'https://cdn.poehali.dev/files/analysis.jpg', 'Аналитика', true, '2024-08-20 10:00:00', NOW()),
('Коллаборации: как найти фит', 'collaborations-guide', 'Совместные треки для роста аудитории', 'Networking в музыке', 'https://cdn.poehali.dev/files/collab.jpg', 'Карьера', true, '2024-08-15 12:00:00', NOW()),
('Голосовая подготовка вокалиста', 'vocal-training', 'Упражнения и техники', 'Здоровье голоса', 'https://cdn.poehali.dev/files/vocal.jpg', 'Обучение', true, '2024-08-10 09:00:00', NOW()),
('Создание вирусного контента', 'viral-content', 'Формулы успешных постов и видео', 'Психология вирусности', 'https://cdn.poehali.dev/files/viral.jpg', 'Продвижение', true, '2024-08-05 11:00:00', NOW()),
('Продюсирование: с чего начать', 'production-basics', 'Основы создания битов', 'Для начинающих битмейкеров', 'https://cdn.poehali.dev/files/production.jpg', 'Для начинающих', true, '2024-07-30 10:00:00', NOW()),
('Работа с блогерами', 'working-with-bloggers', 'Как договориться о коллаборации', 'Инфлюенсер-маркетинг', 'https://cdn.poehali.dev/files/bloggers.jpg', 'Продвижение', true, '2024-07-25 12:00:00', NOW()),
('Брендинг артиста', 'artist-branding', 'Как создать запоминающийся образ', 'Визуал и позиционирование', 'https://cdn.poehali.dev/files/branding.jpg', 'Карьера', true, '2024-07-20 09:00:00', NOW()),
('Spotify для артистов: фичи 2025', 'spotify-for-artists-2025', 'Новые возможности платформы', 'Обновления года', 'https://cdn.poehali.dev/files/spotify-artists.jpg', 'Аналитика', true, '2024-07-15 11:00:00', NOW()),
('Как справиться с выгоранием', 'burnout-prevention', 'Ментальное здоровье артиста', 'Баланс творчества и отдыха', 'https://cdn.poehali.dev/files/burnout.jpg', 'Карьера', true, '2024-07-10 10:00:00', NOW()),
('Искусственный интеллект в музыке', 'ai-in-music', 'Инструменты и этика использования', 'Будущее индустрии', 'https://cdn.poehali.dev/files/ai-music.jpg', 'Тренды', true, '2024-07-05 14:00:00', NOW()),
('Первые 1000 слушателей', 'first-1000-listeners', 'Как набрать начальную аудиторию', 'Стратегия холодного старта', 'https://cdn.poehali.dev/files/1000-listeners.jpg', 'Для начинающих', true, '2024-07-01 09:00:00', NOW())
